name: epiphany-platform
repos:
  - name: m-aws-kubernetes-service
    labels:
      - name: status/grooming-needed
        description: More grooming is required
        color: f7dd1d
      - name: status/hold
        description: Do not start this task
        color: f7dd1d
      - name: status/ready-for-development
        description: This can be taken
        color: f7dd1d
      - name: status/awaiting-more-evidence
        description: Bug requires additional confirmation
        color: f7dd1d
      - name: type/backport
        description: Backport to feature or bug to previous minor versions
        color: 29799e
      - name: type/bug
        description: Bug in existing feature
        color: 29799e
      - name: type/feature-request
        description: New feature requested
        color: 29799e
      - name: type/improvement
        description: Improvement of existing feature (not a bug)
        color: 29799e
      - name: type/spike
        description: Gain knowledge necessary to reduce the risk of a technical approach
        color: 29799e

#name: epiphany-platform
#repos:
#  - name: m-aws-kubernetes-service
#    labels:
#      - priority/critical
#      - priority/high
#      - priority/medium
#      - priority/low
#  - name: m-aws-basic-infrastructure
#    labels:
#      - status/grooming-needed
#      - status/hold
#      - status/ready-for-development
#      - status/awaiting-more-evidence
#      - type/backport
#      - type/bug
#      - type/feature-request
#      - type/improvement
#      - type/investigation
#      - type/management
#      - type/performance
#      - type/spike
#      - priority/critical
#      - priority/high
#      - priority/medium
#      - priority/low
#  - name: m-azure-basic-infrastructure
#    labels:
#      - status/grooming-needed
#      - status/hold
#      - status/ready-for-development
#      - status/awaiting-more-evidence
#      - type/backport
#      - type/bug
#      - type/feature-request
#      - type/improvement
#      - type/investigation
#      - type/management
#      - type/performance
#      - type/spike
#      - priority/critical
#      - priority/high
#      - priority/medium
#      - priority/low
#  - name: m-azure-kubernetes-service
#    labels:
#      - status/grooming-needed
#      - status/hold
#      - status/ready-for-development
#      - status/awaiting-more-evidence
#      - type/backport
#      - type/bug
#      - type/feature-request
#      - type/improvement
#      - type/investigation
#      - type/management
#      - type/performance
#      - type/spike
#      - priority/critical
#      - priority/high
#      - priority/medium
#      - priority/low
